### ISSUE TITLE
Port rnaseq subworkflows to nf-core/modules

### ISSUE THREAD

**Issue by maxulysse** [nf-core/modules#2160]
Please convert each of this as an issue when you start working on one.
(That can be done by clicking on the circle dot `⊙` at the end of the line in the list below, hover on a list item to see it)
And label it with the appropriate pipeline label (ie :`rnaseq`).
Note that a subworkflow can be useful for several pipelines.

- [x] #2264
- [x] #2180 rename to `bam_sort_stats_samtools` @KamilMaliszArdigen 
- [x] new subworkflow bam_stats_samtools @drpatelh 
- [x] #2194 rename to `bedgraph_bedclip_bedgraphtobigwig` @KamilMaliszArdigen 
- [x] #2224 rename to `bam_dedup_stats_samtools_umitools` @KamilMaliszArdigen 
- [x] #2253 @KamilMaliszArdigen 
- [x] #2168 @dmarron
- [x] new subworkflow rseqc `bam_rseqc` @drpatelh
