### ISSUE TITLE
Missing information in meta.yml files

### ISSUE THREAD

**Issue by mashehu** [nf-core/modules#2914]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The new json-schema for the meta.ymls unearthed some missing information in some files. In order to keep a certain standard (and have all modules nicely rendered on the website) the following files need some work (I tagged the authors listed in the files)

The following modules have missing details in their meta.yml (we require a `type` and `description` for each entry in input and output).

- [ ] rseqc/junctionannotation (@drpatelh, @KevinMenden)
- [ ] quast (@drpatelh, @KevinMenden)
- [ ] gatk4_filtervarianttranches (@FriederikeHanssen)
- [ ] controlfreec_freec (@FriederikeHanssen)
- [ ] imputeme_vcftoprs (@lassefolkersen)
- [ ] cellranger_mkgtf (@ggabernet, @Emiller88)

The following modules don't have a description: 
- [ ] phantompeakqualtools (@drpatelh, @Emiller88, @JoseEspinosa)
- [ ] metabat2_metabat2 (@maxibor, @jfy133)
- [ ] khmer_uniquekmers (@JoseEspinosa)
- [ ] gatk4_splitintervals (@nvnieuwk)
- [ ] cnvkit_antitarget (@SusiJo)
- [ ] cnvkit_reference (@SusiJo)
- [ ] cnvkit_target (@SusiJo)
- [ ] gatk_unifiedgenotyper (@ilight1542, @jfy133)
- [ ] gatk4_intervallisttobed (@FriederikeHanssen)

**Comment by jfy133** [comment]
The number of core team members in that list is slightly funny 🤣 (although from very old modules AFAICS)

**Comment by jfy133** [comment]
For my two :point_up:

**Comment by FriederikeHanssen** [comment]
@mashehu I am updating "my" modules at the moment. Do you have more specifics what is wrong with the freec module? I can't see anything in the meta.yml and it looks fine on the website

**Comment by mashehu** [comment]
@FriederikeHanssen freec is missing a description for `snp_position` and intervallistotbed doesn't have a module description (and needs one more keyword).

**Comment by klkeys** [comment]
it's unclear if `imputeme_vcftoprs` is maintained anymore

the [linked Docker image](https://hub.docker.com/r/lassefolkersen/impute-me) apparently no longer exists

the [source code](https://github.com/lassefolkersen/impute-me) is also gone

unless somebody (@lassefolkersen?) can fill the missing information, then I move to nix the module
