### ISSUE TITLE
complete available parabricks tools

### ISSUE THREAD

**Issue by Furentsu** [nf-core/modules#3983]
List of all the Parabricks tools: https://docs.nvidia.com/clara/parabricks/4.0.1/documentation/tooldocs/standalonetools.html

```[tasklist]
### Tasks
- [x] develop haplotypecaller parabricks module
- [x] develop GVCF index parabricks module
- [x] develop GenotypeGVCF parabricks module
```

**Comment by Emiller88** [comment]
#2550 #2555 We have a fewe of these, any particular modules? You could start a task list.

**Comment by Furentsu** [comment]
Yes, I have just added the tasks and I am making pull requests separately for each of the tools (at the moment I have just made the first one for haplotypecaller - #4073)

**Comment by famosab** [comment]
I created a new list which holds all software from parabricks and shows what modules are already available #6782
