### ISSUE TITLE
new module: dragen

### ISSUE THREAD

**Issue by marrip** [nf-core/modules#4026]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

## DNA

```[tasklist]
### Tasks
- [x] Provide ped for for [trio](https://github.com/genome-in-a-bottle/giab_data_indexes) @marrip
- [x] Run trio analysis on [HG002, HG003, HG004](https://github.com/genome-in-a-bottle/giab_data_indexes) @xuyangyuio
- [x] Add remaining output files to Dragen module @marrip
```

## RNA

```[tasklist]
### Tasks
- [x] Check if we already have a list of output files @asr081
- [ ] Check if `.gtf` file is present in Dragen references folder @xuyangyuio
- [x] Find RNA samples @marrip
- [ ] Get access to dragen @marrip
- [ ] run test data @marrip
```

## Methylation

```[tasklist]
### Tasks
- [x] Evaluate [test data](https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR24827403&display=download) @asr081
- [ ] run test data @marrip
```

## Amplicon

```[tasklist]
### Tasks
```

## Single Cell

```[tasklist]
### Tasks
```

**Comment by marrip** [comment]
Options we might not need:
```bash
  --fastq-list arg                                        CSV file specifying list of FASTQs for input
  --fastq-list-sample-id arg                              Only process entries whose 'RGSM' entry matches the given
                                                          Sample ID parameter (for fastq-list.csv input)
  --fastq-list-all-samples arg                            Process all samples in fastq-list file, even when there are
```

**Comment by marrip** [comment]
Input:
```bash
  -1 [ --fastq-file1 ] arg                                FASTQ file to send to card (may be gzipped)
  -2 [ --fastq-file2 ] arg                                Second FASTQ file with paired-end reads (may be gzipped)
  --tumor-fastq1 arg                                      FASTQ file of tumor reads for somatic mode
  --tumor-fastq2 arg                                      Second FASTQ file of tumor reads for somatic mode
```

**Comment by marrip** [comment]
params:

```bash
 -p [ --pair-by-name ] arg                               Whether to use read names to identify read pairs. Valid only for BAM input.
 --append-read-index-to-name arg                         Whether to append /1 or /2 to read names for paired-end
  --pair-suffix-delimiter arg                             Character that delimits paired-end suffixes, e.g. / for /1 and /2
  --aws-s3-region arg                                     Specify the geographical region of AWS S3 buckets
  --strip-input-qname-suffixes arg                        Whether to strip /1 or /2 from input read names
```

**Comment by marrip** [comment]
CMD ["/bin/bash"]
RUN RUN yum install unzip wget -y # buildkit
RUN RUN yum install which -y # buildkit
RUN RUN yum config-manager --enable ol8_codeready_builder # buildkit
RUN RUN yum install oracle-epel-release-el8 -y # buildkit
RUN RUN yum install git -y # buildkit
RUN RUN yum install perl -y # buildkit
RUN RUN yum install R -y # buildkit
RUN RUN yum install bc dkms gdb rsync smartmontools sos time -y # buildkit
RUN RUN yum install kernel kernel-devel -y # buildkit
RUN RUN yum install hostname -y # buildkit
COPY ./uname.sh /usr/bin/uname # buildkit
        usr/
        usr/bin/
        usr/bin/uname

COPY dragen-4.2.4-9.el8.x86_64.run . # buildkit
        dragen-4.2.4-9.el8.x86_64.run

RUN RUN /bin/sh dragen-4.2.4-9.el8.x86_64.run; rm -rf dragen-4.2.4-9.el8.x86_64.run  \
        && rm -rf /dragen_software # buildkit

**Comment by marrip** [comment]
merged
