### ISSUE TITLE
Renovate nice-to-haves

### ISSUE THREAD

**Issue by Emiller88** [nf-core/modules#4217]
Just some ideas of where we can do with this

```[tasklist]
### Tasks
- [ ] #4216 
- [ ] Group conda and docker updates
- [ ] Try to update snapshots
- [ ] If versions are the only thing updated in the snapshot, merge
- [ ] Automerging with the above passing
```

**Comment by Emiller88** [comment]
Maybe we could make a comment on all Renovate PRs that links to this issue 🤔

**Comment by Emiller88** [comment]
Need to add comments to all the conda packages. Just need a script to write the comments for every single conda dependancy. 

But there isn't a point while we have the mulled containers because they just have to be bumped manually, and that's just not gonna happen.
