### ISSUE TITLE
update modules: nextclade/run and nextclade/datasetget

### ISSUE THREAD

**Issue by nmshahir** [nf-core/modules#6245]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, but have not added myself because github won't let me at this time
```[tasklist]
### Tasks
- [x] Update nextclade/run
- [x] Update nextclade/datasetget
- [x] Add test for nextclade/datasetget
- [x] Add test for nextclade/run
```
